### ISSUE TITLE
ERROR 9400 nodejs.ENOENTError: spawn 压测产生异常错误

### ISSUE THREAD

**Issue by a526672351** [aliyun-node/commands#17]
ERROR 9400 nodejs.ENOENTError: spawn F:\new\InternationalStation-admin\node_modules\_commandx@1.4.0@commandx\get_processes_count ENOENT
at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

> 附加数据

code: 'ENOENT'
errno: 'ENOENT'
syscall: 'spawn F:\\new\\InternationalStation-admin\\node_modules\\_commandx@1.4.0@commandx\\get_processes_count'
path: 'F:\\new\\InternationalStation-admin\\node_modules\\_commandx@1.4.0@commandx\\get_processes_count'

**Comment by JacksonTian** [comment]
亲，Node.js 性能平台目前不支持 Windows 下运行。请仅在  Mac/Linux 下开启 agenthub/agentx。

**Comment by a526672351** [comment]
@JacksonTian 不是windows，是centos 6.5，跑的是vm虚拟机环境的cent OS

**Comment by JacksonTian** [comment]
亲 如果是在 centOS 里，路径不应该存在 F:\ 吧，你是不是跑错环境了。

**Comment by a526672351** [comment]
@JacksonTian 还真是部署的时候，有一台是window机子，没问题了，谢谢
