### ISSUE TITLE
get_disk_usage和get_processes_count不知名报错

### ISSUE THREAD

**Issue by DanielWLam** [aliyun-node/commands#9]
请问一下，是不是因为在windows下，以下两个脚本会报错，没有考虑到windows的情况？
```js
#!/bin/bash

df -P


#!/bin/bash

ps -e -o pid,command | grep -E "$1 |$1$" | grep -vE 'grep|get_processes_count' -c

```

```js
2017-01-17 14:20:31,231 ERROR 7956 nodejs.ENOENTError: spawn E:\project\ask-backend\node_modules\commandx\get_disk_usage ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
code: 'ENOENT'
errno: 'ENOENT'
syscall: 'spawn E:\\project\\ask-backend\\node_modules\\commandx\\get_disk_usage'
path: 'E:\\project\\ask-backend\\node_modules\\commandx\\get_disk_usage'
spawnargs: []
cmd: 'E:\\project\\ask-backend\\node_modules\\commandx\\get_disk_usage'
name: 'ENOENTError'
pid: 7956
hostname: uc-PC

2017-01-17 14:20:31,263 ERROR 7956 nodejs.ENOENTError: spawn E:\project\ask-backend\node_modules\commandx\get_processes_count ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
code: 'ENOENT'
errno: 'ENOENT'
syscall: 'spawn E:\\project\\ask-backend\\node_modules\\commandx\\get_processes_count'
path: 'E:\\project\\ask-backend\\node_modules\\commandx\\get_processes_count'
spawnargs: [ 'node' ]
cmd: 'E:\\project\\ask-backend\\node_modules\\commandx\\get_processes_count node'
name: 'ENOENTError'
pid: 7956
hostname: uc-PC
```

**Comment by JacksonTian** [comment]
不支持在Windows下跑。

另外可能需要升级下commandx
